analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.768092
  lightness: 0.283717
  rhythmicContrast: 0.426809
  saturation: 0.5
cta: {}
layout_spectrum: 0.212171
name: halloran
opengraph: {}
purpose: {}
typography_spectrum: 0.51069
